name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master # master 分支有 push 行为时就触发这个 action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
        # 修改github action不管用的问题
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }} # secret 名
          PUBLISH_REPOSITORY: camillechang/camillechang.github.io # 公共仓库，格式：GitHub 用户名/仓库名
          BRANCH: master # 分支，我这里是推送到wkxk/wkxk.github.io仓库里的master分支(根据自己的仓库进行填写)
          PUBLISH_DIR: ./public # 部署 public 目录下的文件
        run: |
          npm install hexo-cli -g
          npm install

      - name: Deploy
        # uses: theme-keep/hexo-deploy-github-pages-action@master # 使用专门部署 Hexo 到 GitHub pages 的 action
        run: |
          hexo clean
          hexo deploy -g
