name: CI

on:
  push:
    branches:
      - master

env:
  GIT_USER: Camille
  THEME_REPO: camillechang/hugo-theme-keep-forblog
  THEME_BRANCH: master
  DEPLOY_REPO: camillechang/camillechang.github.io
  DEPLOY_BRANCH: master
  CNAME: camillechang.com

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout theme repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/keep

      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY}} #sourcecode里面的sercert
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          # replace file with my blog config
          cp _config.keep.yml themes/keep/_config.yml

      - name: Install dependencies
        run: |
          npm install
          npm run build
          npm run clean

      - name: Deploy hexo
        run: |
          npm run deploy
